name: Efficiency Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  examples-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: ./.venv/  
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - run: python -m venv ./.venv && . ./.venv/bin/activate && 
            pip install -r requirements.txt && python setup.py install
        if: steps.cache-venv.outputs.cache-hit != 'true'
      
      - name: First Example
        run: . ./.venv/bin/activate && python examples/structure.py
      - name: Second Example
        run: . ./.venv/bin/activate && python examples/async_download.py