name: Efficiency Test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - uses: actions/cache@v2
        id: cache-venv  # name for referring later
        with:
          path: ./.venv/  # what we cache: the virtualenv
          # The cache key depends on requirements.txt
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      # Build a virtualenv, but only if it doesn't already exist
      - run: python -m venv ./.venv && . ./.venv/bin/activate && 
            pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      # Run tests
      # Note that you have to activate the virtualenv in every step
      # because GitHub actions doesn't preserve the environment
      - name: Setup
        run: . ./.venv/bin/activate && python setup.py install
      - name: First Example
        run: . ./.venv/bin/activate && python examples/structure.py
      - name: Second Example
        run: . ./.venv/bin/activate && python examples/async_download.py